### ISSUE TITLE
Interested

### ISSUE THREAD

**Issue by kiselli** [naglis/misc-addons#1]
Hi @naglis,

I'm very interested in this Project. Sadly there is not much Information in the Readme :(

How is your work proceeding? What features should the final version have?

**Comment by naglis** [comment]
Hello @kiselli,

this is mostly developed for our company internal purposes. The feature we need is import of OpenProject member monthly time entries into Odoo. The time entries are exported in OpenProject by going `https://<your_openproject_instance>/time_entries/` and selecting *Report*. The time entries are exported in CSV format, which looks something like this:

```
Member,2016-08-01,2016-08-02,...,2016-08-31,Totals
Nancy Wheeler,1.1,1.2,...,0.0,2.3
Will Byers,2.2,3.3,...,1.0,6.5
``` 

During import in Odoo, you are able to map the OpenProject user with the employee in Odoo. Then, a timesheet (`hr_timesheet_sheet.sheet`) record is created for each employee with the timesheet containing lines with hours worked on each day in the period of the CSV file (a month/week, etc.).

I guess it is specific to the way we do things in our company, so please feel free to adapt the module to your needs.

And, you are totally right - the README would really benefit from a more detailed description. I will try to improve it in the coming day or two.
