### ISSUE TITLE
Disable Database Manager: Cannot go to login page 

### ISSUE THREAD

**Issue by fraharijaona** [naglis/misc-addons#13]
The addon works well, but if I run server with --no-database-list parameter. User can't go to login page anymore.
I think it is due to the way that /web/login/ redirects to /web/database/selector, but it will be much prettier if the error notification is shown only on /web/database/manager not to /web/database/selector.
Thanks

**Comment by naglis** [comment]
Hi @fraharijaona, thanks for the report.

I am assuming your have multiple databases? If so, does going `/web?db=<your db>` allow you to login into `<your db>`?

I'll check how/if this is fixed in v11.

**Comment by naglis** [comment]
The behavior with multiple databases appears to be the same in Odoo v11 - if there are multiple databases, the database selector window is disabled if `--no-database-list` is used, so either a default database should be set via `-d`, `--database` CLI parameter or the `db_name` configuration parameter, or users should specify the DB name in the URL, e.g.: `/web/login?db=<mydatabase>`. I've added a note about it in f1198432724bf92af214d13f99e1536b36bf4b38.
