### ISSUE TITLE
Question on the open-project connector

### ISSUE THREAD

**Issue by safecoms** [naglis/misc-addons#3]
Hi @naglis 
Do you intend to improve the open project connector so the connection can be both ways?

So Open-project could get data from Odoo as well. Like the timesheet entries from Odoo and the project created in Odoo?

**Comment by naglis** [comment]
Hi @safecoms,

> Do you intend to improve the open project connector so the connection can be both ways?

Unfortunately, no, as I have no need for both way synchronization.

> So Open-project could get data from Odoo as well. Like the timesheet entries from Odoo and the project created in Odoo?

AFAICT, the current version of the OpenProject API does not support creating [projects](http://docs.openproject.org/apiv3-doc/#projects) via API, same goes for time entries, but at least for time entries [create support is planned](https://community.openproject.com/projects/openproject/work_packages/26108/activity).

Closing this, please feel free to re-open if you have further related questions.
