### ISSUE TITLE
Do you plan to migrate connector_openproject to v11?

### ISSUE THREAD

**Issue by rafaelbn** [naglis/misc-addons#6]
Hi @naglis ,

- Do you plan migration to v11 of https://github.com/naglis/misc-addons/tree/10.0/connector_openproject
- Have you thanked to contribute your connector to OCA?

Thanks
Regards

**Comment by naglis** [comment]
Hello @rafaelbn,

thank you for your question.

> Do you plan migration to v11 of https://github.com/naglis/misc-addons/tree/10.0/connector_openproject

No, not in the near future, as currently I do not have a need for it in v11. Nevertheless, I would welcome PRs or if you or your company would like to sponsor the migration then that would be welcome as well.

> Have you thanked to contribute your connector to OCA?

Unfortunately, transfering the addon to OCA is not something I would feel comfortable with.

I hope I have answered your questions, so I will close the issue. Feel free to reopen if you have additional questions.

**Comment by rafaelbn** [comment]
Hi @naglis,

We could migrate it to v11 only if it goes under OCA umbrella. Just because all  the work we do is for OCA and we work only with OCA modules.

I supposed as you work with https://github.com/oca/connector you would like increase visibility and increase contributors :-)

Thank you form answering :+1

**Comment by pedrobaeza** [comment]
Hi @naglis, as said by my colleague, we don't do anything outside of OCA, as we need some verifiable quality, community rules, etc, so we can do the work of migrating the module (if the customer accepts the budget) only moving it to OCA. Why don't you want it? Strictly speaking, we can do it already without your consent (respecting attribution) as this is open source, but of course it's not very kind, and that's why we ask you.

**Comment by naglis** [comment]
> Strictly speaking, we can do it already without your consent (respecting attribution) as this is open source, but of course it's not very kind, and that's why we ask you.

@pedrobaeza, as long as the terms of the license are respected, you have my blessing :smiley: :+1:

**Comment by pedrobaeza** [comment]
Of course license is in the pack of things to respect :smiley: 

But I'm curious why do you prefer not to move it. I know that sometimes it means more bureaucracy, but at the end, you have more infrastructure at your service (Travis, runbot) and other known benefits as you know as you are already an OCA contributor.
